# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ackleys <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Ackleys`, sum, x, N))
}

AluffiPentini <- function(sum, x, N) {
    invisible(.Call(`_castOpt_AluffiPentini`, sum, x, N))
}

BeckerLago <- function(sum, x, N) {
    invisible(.Call(`_castOpt_BeckerLago`, sum, x, N))
}

Bohachevsky1 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Bohachevsky1`, sum, x, N))
}

Bohachevsky2 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Bohachevsky2`, sum, x, N))
}

Branin <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Branin`, sum, x, N))
}

Camel3 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Camel3`, sum, x, N))
}

Camel6 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Camel6`, sum, x, N))
}

CosMix2 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_CosMix2`, sum, x, N))
}

CosMix4 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_CosMix4`, sum, x, N))
}

DekkersAarts <- function(sum, x, N) {
    invisible(.Call(`_castOpt_DekkersAarts`, sum, x, N))
}

Easom <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Easom`, sum, x, N))
}

EMichalewicz <- function(sum, x, N) {
    invisible(.Call(`_castOpt_EMichalewicz`, sum, x, N))
}

Expo <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Expo`, sum, x, N))
}

GoldPrice <- function(sum, x, N) {
    invisible(.Call(`_castOpt_GoldPrice`, sum, x, N))
}

Griewank <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Griewank`, sum, x, N))
}

Gulf <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Gulf`, sum, x, N))
}

Hartman3 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Hartman3`, sum, x, N))
}

Hartman6 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Hartman6`, sum, x, N))
}

Hosaki <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Hosaki`, sum, x, N))
}

Kowalik <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Kowalik`, sum, x, N))
}

LM1 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_LM1`, sum, x, N))
}

LM2n10 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_LM2n10`, sum, x, N))
}

LM2n5 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_LM2n5`, sum, x, N))
}

McCormic <- function(sum, x, N) {
    invisible(.Call(`_castOpt_McCormic`, sum, x, N))
}

MeyerRoth <- function(sum, x, N) {
    invisible(.Call(`_castOpt_MeyerRoth`, sum, x, N))
}

MieleCantrell <- function(sum, x, N) {
    invisible(.Call(`_castOpt_MieleCantrell`, sum, x, N))
}

Modlangerman <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Modlangerman`, sum, x, N))
}

ModRosenbrock <- function(sum, x, N) {
    invisible(.Call(`_castOpt_ModRosenbrock`, sum, x, N))
}

MultiGauss <- function(sum, x, N) {
    invisible(.Call(`_castOpt_MultiGauss`, sum, x, N))
}

Neumaier2 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Neumaier2`, sum, x, N))
}

Neumaier3 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Neumaier3`, sum, x, N))
}

Paviani <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Paviani`, sum, x, N))
}

Periodic <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Periodic`, sum, x, N))
}

PowellQ <- function(sum, x, N) {
    invisible(.Call(`_castOpt_PowellQ`, sum, x, N))
}

PriceTransistor <- function(sum, x, N) {
    invisible(.Call(`_castOpt_PriceTransistor`, sum, x, N))
}

Rastrigin <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Rastrigin`, sum, x, N))
}

Rosenbrock <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Rosenbrock`, sum, x, N))
}

Salomon <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Salomon`, sum, x, N))
}

Schaffer1 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Schaffer1`, sum, x, N))
}

Schaffer2 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Schaffer2`, sum, x, N))
}

Schubert <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Schubert`, sum, x, N))
}

Schwefel <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Schwefel`, sum, x, N))
}

Shekel10 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Shekel10`, sum, x, N))
}

Shekel5 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Shekel5`, sum, x, N))
}

Shekel7 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Shekel7`, sum, x, N))
}

Shekelfox5 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Shekelfox5`, sum, x, N))
}

Wood <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Wood`, sum, x, N))
}

Zeldasine10 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Zeldasine10`, sum, x, N))
}

Zeldasine20 <- function(sum, x, N) {
    invisible(.Call(`_castOpt_Zeldasine20`, sum, x, N))
}

reg_beta <- function(sum, x, N, data) {
    invisible(.Call(`_castOpt_reg_beta`, sum, x, N, data))
}

